---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: simple-k8s-webserver
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/tobywan/simple-k8s-webserver
